name: Publish to Hangar
on:
  push:
    branches:
      - master
      - dev

jobs:
  publish:
    if: github.repository_owner == 'ViaVersion'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
        run: ./gradlew build publishAllPublicationsToHangar
